CC  = cl
LINK = link

TARGETS : ANBUIMSC.EXE

CFLAGS = /nologo /IMSC700 /WX /Ox

clean:
    del *.obj
    del ANBUIMSC.EXE

ad_obj.obj :
ad_text.obj :
ad_ui.obj :
pl_dos.obj :
anbui.obj :
ad_test.obj :

ANBUIMSC.EXE : clean ad_obj.obj ad_text.obj ad_ui.obj pl_dos.obj anbui.obj ad_test.obj
    $(LINK) ad_obj+ad_text+ad_ui+pl_dos+anbui+ad_test,ANBUIMSC.EXE;


.c.obj:
    $(CC) $(CFLAGS) /c $<
